### ISSUE TITLE
Reference Parser doesn't allow empty UNIT/HELP descriptors

### ISSUE THREAD

**Issue by sinkingpoint** [OpenObservability/OpenMetrics#231]
In the spec, we have:

```
The value of a UNIT or HELP line MAY be empty. This MUST be treated as if no metadata line for the MetricFamily existed.
```

which implies to me that something like this is valid:

```
# TYPE a counter
# HELP a
# UNIT a
a 1
```

however the reference python parser balks at such an input:

```
python parser.py < ../../testdata/parsers/info_type/metrics 
Traceback (most recent call last):
  File "/home/colin/repos/openmetrics-parser/OpenMetrics/tests/implementations/prometheus_client_python_parser/parser.py", line 6, in <module>
    print(list(families))
  File "/home/colin/scratch/lib/python3.9/site-packages/prometheus_client/openmetrics/parser.py", line 24, in text_string_to_metric_families
    for metric_family in text_fd_to_metric_families(StringIO.StringIO(text)):
  File "/home/colin/scratch/lib/python3.9/site-packages/prometheus_client/openmetrics/parser.py", line 511, in text_fd_to_metric_families
    raise ValueError("Invalid line: " + line)
ValueError: Invalid line: # UNIT a
```

**Comment by brian-brazil** [comment]
The parser is correctly rejecting this input, as it is missing the space after the metric name for the HELP/UNIT lines. The sample is also missing the _total, leading to a metric clash.
